// apps/mobile/src/components/RecipeImport.tsx
import { useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { parseRecipeFromHtml, type ParsedRecipe } from '@macrolog/core';
import { useT } from '@/i18n';
import * as haptics from '@/lib/haptics';
import { useTheme, useThemedStyles, type Theme } from '@/lib/theme-context';
import { font, radius, space } from '@/theme';
import type { RecipeEstimate } from '@/components/RecipeBuilder';

interface Props {
  onApply: (estimate: RecipeEstimate) => void;
  onCancel: () => void;
}

const FETCH_TIMEOUT_MS = 8000;
// A browser-ish UA — some recipe sites 403 the default RN agent.
const UA = 'Mozilla/5.0 (compatible; IgniaRecipeImporter/1.0; +https://ignia.fit)';

/**
 * Recipe-URL import (mobile). Unlike the web, React Native's fetch is not
 * CORS-bound, so the app fetches the recipe page directly and parses its
 * JSON-LD via the shared core parser (`parseRecipeFromHtml`) — no Cloud
 * Function needed. When the page publishes nutrition, one serving is emitted
 * to prefill the manual form (same path as the recipe builder).
 */
export function RecipeImport({ onApply, onCancel }: Props) {
  const t = useT();
  const styles = useThemedStyles(createStyles);
  const { colors } = useTheme();
  const [url, setUrl] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<ParsedRecipe | null>(null);

  const perServingKcal = result?.perServing?.calories ?? 0;
  const perServingProtein = result?.perServing?.protein ?? null;
  const canApply = perServingKcal > 0;

  async function fetchRecipe() {
    const raw = url.trim();
    if (!raw || loading) return;
    let href: string;
    try {
      const u = new URL(raw);
      if (u.protocol !== 'https:' && u.protocol !== 'http:') throw new Error('scheme');
      href = u.href;
    } catch {
      setError(t('recipeImport.errInvalidUrl'));
      return;
    }
    setLoading(true);
    setError(null);
    setResult(null);
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
    try {
      const res = await fetch(href, {
        headers: { 'User-Agent': UA, Accept: 'text/html,application/xhtml+xml' },
        signal: controller.signal,
      });
      if (!res.ok) throw new Error(`status ${res.status}`);
      const html = await res.text();
      const parsed = parseRecipeFromHtml(html);
      if (!parsed || parsed.perServing?.calories == null) {
        setError(t('recipeImport.noNutrition'));
        return;
      }
      haptics.success();
      setResult(parsed);
    } catch {
      setError(t('recipeImport.errFetch'));
    } finally {
      clearTimeout(timer);
      setLoading(false);
    }
  }

  function apply() {
    if (!result || !canApply) return;
    haptics.success();
    onApply({
      calories: perServingKcal,
      protein: perServingProtein ?? undefined,
      mealLabel: result.name.trim(),
    });
  }

  return (
    <View style={styles.wrap}>
      <View style={styles.head}>
        <Text style={styles.title}>{t('recipeImport.title')}</Text>
        <TouchableOpacity onPress={onCancel} hitSlop={12} accessibilityRole="button">
          <Text style={styles.cancel}>{t('common.cancel')}</Text>
        </TouchableOpacity>
      </View>
      <Text style={styles.desc}>{t('recipeImport.desc')}</Text>

      <View style={styles.row}>
        <TextInput
          style={[styles.input, styles.urlInput]}
          placeholder={t('recipeImport.urlPlaceholder')}
          placeholderTextColor={colors.faint}
          value={url}
          onChangeText={(v) => { setUrl(v); if (error) setError(null); }}
          autoCapitalize="none"
          autoCorrect={false}
          keyboardType="url"
          returnKeyType="go"
          onSubmitEditing={fetchRecipe}
          testID="recipe-import-url"
        />
        <TouchableOpacity
          style={[styles.fetchBtn, (loading || !url.trim()) && styles.btnDisabled]}
          onPress={fetchRecipe}
          disabled={loading || !url.trim()}
          accessibilityRole="button"
          testID="recipe-import-fetch"
        >
          <Text style={styles.fetchText}>
            {loading ? t('recipeImport.fetching') : t('recipeImport.fetch')}
          </Text>
        </TouchableOpacity>
      </View>

      {error ? (
        <Text style={styles.error} accessibilityRole="alert" accessibilityLiveRegion="polite">
          {error}
        </Text>
      ) : null}

      {result ? (
        <ScrollView keyboardShouldPersistTaps="handled" style={styles.resultScroll}>
          <View style={styles.resultCard}>
            <Text style={styles.resultName}>{result.name || t('recipeImport.untitled')}</Text>
            <Text style={styles.resultMeta}>
              {perServingKcal} kcal
              {perServingProtein != null ? ` · ${perServingProtein}${t('recipeImport.proteinUnit')}` : ''}
              {' '}{t('recipeImport.perServing')}
              {result.servings ? ` · ${t('recipeImport.servings', { n: result.servings })}` : ''}
            </Text>
            {result.ingredients.length ? (
              <Text style={styles.resultIng}>
                {t('recipeImport.ingredientCount', { n: result.ingredients.length })}
              </Text>
            ) : null}
          </View>
        </ScrollView>
      ) : null}

      {result ? (
        <TouchableOpacity
          style={[styles.apply, !canApply && styles.btnDisabled]}
          onPress={apply}
          disabled={!canApply}
          accessibilityRole="button"
          testID="recipe-import-apply"
        >
          <Text style={styles.applyText}>{t('recipeImport.useThis')}</Text>
        </TouchableOpacity>
      ) : null}
    </View>
  );
}

const createStyles = ({ colors }: Theme) => StyleSheet.create({
  wrap: { minHeight: 320, gap: space.sm },
  head: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  title: { fontSize: font.h3, color: colors.ink, fontWeight: '800' },
  cancel: { fontSize: font.small, color: colors.muted, fontWeight: '700' },
  desc: { fontSize: font.small, color: colors.muted, lineHeight: 18 },
  row: { flexDirection: 'row', gap: space.xs, alignItems: 'center' },
  input: {
    backgroundColor: colors.inputBg,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.md,
    paddingHorizontal: space.md,
    paddingVertical: space.sm,
    color: colors.ink,
    fontSize: font.body,
  },
  urlInput: { flex: 1 },
  fetchBtn: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.ink,
    borderRadius: radius.pill,
    paddingHorizontal: space.lg,
    paddingVertical: space.sm,
  },
  btnDisabled: { opacity: 0.4 },
  fetchText: { fontSize: font.small, fontWeight: '800', color: colors.ink },
  error: { fontSize: font.small, color: colors.danger, lineHeight: 18 },
  resultScroll: { maxHeight: 180 },
  resultCard: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radius.md,
    padding: space.md,
    gap: 2,
  },
  resultName: { fontSize: font.body, color: colors.ink, fontWeight: '700' },
  resultMeta: { fontSize: font.small, color: colors.muted },
  resultIng: { fontSize: font.small, color: colors.faint, marginTop: 2 },
  apply: {
    backgroundColor: colors.accent,
    borderRadius: radius.pill,
    paddingVertical: space.md,
    alignItems: 'center',
  },
  applyText: { fontSize: font.body, fontWeight: '800', color: colors.white },
});

// src/app/components/recipe-import/recipe-import.component.ts
import {
  ChangeDetectionStrategy, Component, inject, output, signal,
} from '@angular/core';
import { TranslocoDirective } from '@jsverse/transloco';
import { LucideAngularModule } from 'lucide-angular';
import { parseRecipeFromHtml, type ParsedRecipe } from '@macrolog/core';
import { CallableGateway } from '../../services/callable.gateway';
import { TranslationService } from '../../services/translation.service';
import { extractErrorCode } from '../../models/error-codes';
import type { MacroEstimate } from '../../models/macro-estimate';
import { UiButton } from '../ui/button.component';

/**
 * Recipe-URL import. Paste a recipe link → a hardened Cloud Function fetches
 * the page and returns its JSON-LD → the shared core parser (`parseRecipeFromHtml`)
 * turns it into an editable per-serving draft. When the page publishes a
 * nutrition block, one serving is emitted as a MacroEstimate so the host
 * entry sheet prefills the manual form for review/save (same path as the
 * recipe builder). Pages without nutrition surface a friendly "no data" note.
 */
@Component({
  selector: 'app-recipe-import',
  standalone: true,
  imports: [TranslocoDirective, LucideAngularModule, UiButton],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ng-container *transloco="let t">
    <div style="padding: 12px; background: var(--v2-paper-2); border: 1px solid var(--v2-rule); border-radius: var(--v2-radius-md);">
      <div class="flex items-center justify-between mb-3">
        <div>
          <div class="v2-body" style="font-weight: 500;">{{ t('v2.recipeImport.title') }}</div>
          <p class="v2-caption mt-0.5">{{ t('v2.recipeImport.desc') }}</p>
        </div>
        <ui-button variant="ghost" size="sm" (click)="closed.emit()" [ariaLabel]="t('v2.recipeImport.closeAria')">
          <lucide-icon name="x" [size]="14" />
        </ui-button>
      </div>

      <div class="flex gap-2">
        <input
          type="url"
          inputmode="url"
          maxlength="2048"
          class="flex-1"
          style="padding: var(--v2-space-2) var(--v2-space-3); background: var(--v2-paper); border: 1px solid var(--v2-rule); border-radius: var(--v2-radius-sm); font-family: var(--v2-font-sans); color: var(--v2-ink); min-height: var(--v2-tap-min);"
          [placeholder]="t('v2.recipeImport.urlPlaceholder')"
          [attr.aria-label]="t('v2.recipeImport.urlLabel')"
          [value]="url()"
          (input)="onUrlInput($event)"
          (keydown.enter)="fetch()" />
        <ui-button variant="secondary" size="md" (click)="fetch()" [disabled]="loading() || !url().trim()">
          @if (loading()) { {{ t('v2.recipeImport.fetching') }} }
          @else { {{ t('v2.recipeImport.fetch') }} }
        </ui-button>
      </div>

      @if (error()) {
        <p class="v2-caption mt-2" role="alert" style="color: var(--v2-danger);">{{ error() }}</p>
      }

      @if (result(); as r) {
        <div class="v2-card mt-3 p-3" style="background: var(--v2-paper);">
          <div class="v2-body" style="font-weight: 600;">{{ r.name || t('v2.recipeImport.untitled') }}</div>
          <p class="v2-caption mt-0.5">
            {{ perServingKcal() }} kcal
            @if (perServingProtein() != null) {
              · {{ perServingProtein() }}{{ t('v2.recipeImport.proteinUnit') }}
            }
            {{ t('v2.recipeImport.perServing') }}
            @if (r.servings) { · {{ t('v2.recipeImport.servings', { n: r.servings }) }} }
          </p>
          @if (r.ingredients.length) {
            <p class="v2-caption mt-1" style="color: var(--v2-faint);">
              {{ t('v2.recipeImport.ingredientCount', { n: r.ingredients.length }) }}
            </p>
          }
          <div class="mt-3">
            <ui-button variant="primary" size="md" [block]="true" (click)="apply()" [disabled]="!canApply()">
              {{ t('v2.recipeImport.useThis') }}
            </ui-button>
          </div>
        </div>
      }
    </div>
    </ng-container>
  `,
})
export class RecipeImportComponent {
  private readonly callables = inject(CallableGateway);
  private readonly translation = inject(TranslationService);

  readonly estimated = output<MacroEstimate>();
  readonly closed = output<void>();

  protected readonly url = signal('');
  protected readonly loading = signal(false);
  protected readonly error = signal<string | null>(null);
  protected readonly result = signal<ParsedRecipe | null>(null);

  protected onUrlInput(e: Event): void {
    this.url.set((e.target as HTMLInputElement).value);
    if (this.error()) this.error.set(null);
  }

  protected perServingKcal(): number {
    return this.result()?.perServing?.calories ?? 0;
  }

  protected perServingProtein(): number | null {
    return this.result()?.perServing?.protein ?? null;
  }

  /** Only importable when the page gave us at least a per-serving calorie
   *  number — that's what the manual form needs. */
  protected canApply(): boolean {
    return this.perServingKcal() > 0;
  }

  protected async fetch(): Promise<void> {
    const url = this.url().trim();
    if (!url || this.loading()) return;
    this.loading.set(true);
    this.error.set(null);
    this.result.set(null);
    try {
      const { html } = await this.callables.call<{ url: string }, { html: string }>(
        'importRecipe', { url },
      );
      const parsed = parseRecipeFromHtml(html);
      if (!parsed || parsed.perServing?.calories == null) {
        this.error.set(this.translation.t('v2.recipeImport.noNutrition'));
        return;
      }
      this.result.set(parsed);
    } catch (err) {
      const code = extractErrorCode(err);
      const key = code === 'RECIPE_URL_INVALID' ? 'v2.recipeImport.errInvalidUrl'
        : code === 'RECIPE_NOT_FOUND' ? 'v2.recipeImport.noNutrition'
        : code === 'RATE_LIMITED' ? 'v2.recipeImport.errRateLimited'
        : 'v2.recipeImport.errFetch';
      this.error.set(this.translation.t(key));
    } finally {
      this.loading.set(false);
    }
  }

  protected apply(): void {
    const r = this.result();
    if (!r || !this.canApply()) return;
    this.estimated.emit({
      calories: this.perServingKcal(),
      protein: this.perServingProtein(),
      label: r.name.trim(),
    });
    this.closed.emit();
  }
}
